### ISSUE TITLE
encode and decode longitutde and latitude are not consistent

### ISSUE THREAD

**Issue by qwlong** [google/open-location-code#134]
![image](https://user-images.githubusercontent.com/607963/36010408-3892e828-0d8c-11e8-9664-40d3de465c97.png)
![image](https://user-images.githubusercontent.com/607963/36010459-7ddc8f10-0d8c-11e8-9faf-eea6fadc2ea7.png)
`
2.3.0 :020 > olc.encode(43.845825324701, 87.6474347905425)
 => "8MM9RJWW+8X" 
2.3.0 :021 > [olc.decode('8MM9RJWW+8X').latitude_center, olc.decode('8MM9RJWW+8X').longitude_center]
 => [43.845812499999994, 87.6474375] 
2.3.0 :022 > olc.decode('8MM9RJWW+8X')
 => #<PlusCodes::CodeArea:0x00000009ab8458 @south_latitude=43.845749999999995, @west_longitude=87.647375, @latitude_height=(1/8000), @longitude_width=(1/8000), @latitude_center=43.845812499999994, @longitude_center=87.6474375> 
`

**Comment by bocops** [comment]
@qwlong Each plus code refers to a surface area, not a single surface point.

In your example, you are using a code length of 10 while encoding, which means that the area being addressed by the resulting plus code is 0.000125° x 0.000125°, and is supposed to contain the original location.

When decoding, you are retrieving the center location of that area, which can have a difference to the location you started with of up to half of the height and width (0.0000625°). In your example, the differences are around 10⁻⁵ and 2*10⁻⁶, respectively. Not an error.
