### ISSUE TITLE
Add pip package for python project

### ISSUE THREAD

**Issue by pokey** [google/open-location-code#137]
It would be great if the python project were installable via pip.

**Comment by MarcusTheSmith** [comment]
Has this been worked at all?

**Comment by zongweil** [comment]
No, haven't gotten around to it. I'll try to take a look in the next couple weeks.

**Comment by virtadpt** [comment]
Please do.  I just ran into this as a showstopper.

**Comment by zongweil** [comment]
The python library is available on PyPi now: https://pypi.org/project/openlocationcode/

Please give it a try and let me know if you run into any issues.

**Comment by virtadpt** [comment]
Local test passed.
Built, tested locally, and deployed.
It has to be referenced this way: `from openlocationcode import openlocationcode`

**Comment by zongweil** [comment]
Thanks @virtadpt, changing the import fixed the test in #356. Closing this issue since the library is published and confirmed working!
