### ISSUE TITLE
Consider adding R's olctools

### ISSUE THREAD

**Issue by hrbrmstr** [google/open-location-code#139]
@ironholds created https://github.com/Ironholds/olctools back in 2016. It really should be in this list of OLC implementations.

**Comment by drinckes** [comment]
Sounds good to me. I'd suggest a top level 'other' directory with a markdown file that just lists them alphabetically. If you want to send me a pull request I'd be happy to take a look at it.

**Comment by drinckes** [comment]
... and nobody did. I'm going to add a page to the wiki and migrate some of the existing implementations that just have a README.md file there.

**Comment by drinckes** [comment]
Done!
