### ISSUE TITLE
Define how to render in right-to-left languages

### ISSUE THREAD

**Issue by dharkness** [google/open-location-code#142]
I assume the plus code will be written unchanged (left-to-right) even in RTL languages, but it would be good to specify it. If English were RTL, this is what I'd expect:

> .there weren't you but 23456789+23 to went I

**Comment by zongweil** [comment]
Yes, plus codes will keep the same format in a RTL language. Can you clarify what you mean by specifying it? Do you mean to reverse the plus code digits in a RTL language?

**Comment by dharkness** [comment]
No, I'm simply suggesting that someone add language to the specification spelling out how to render plus codes in RTL languages. Don't leave it open to interpretation for implementors.

**Comment by zongweil** [comment]
Got it. Thanks for the clarification. I'll start a thread internally about being explicit regarding RTL languages.
