### ISSUE TITLE
Plus codes in Google Maps

### ISSUE THREAD

**Issue by amchisty** [google/open-location-code#146]
Well, a couple of days back I noticed a nice feature (Plus Codes) in Google maps and immediately forwarded the screenshots and informed my friends to use it.

I checked again yesterday, it has disappeared..why what happened.

It would be nice if we could copy the code and send on social media messengers to locate our address.

**Comment by drinckes** [comment]
Hi, could you explain what you saw? If it's the plus code line on a business information card, on a smart phone, that's only shown for businesses in a few countries at the moment (BR, CV, NG, SO, ID, IN, RU).

Was that it?

**Comment by seanmavley** [comment]
Currently showing in Ghana too. Just saying

**Comment by nickmccurdy** [comment]
Is this only available in mobile apps so far? I don't see it on the Google Maps site on desktop.

**Comment by drinckes** [comment]
Yes, @zongweil is correct. At the moment it's mobile only. Revealing in desktop maps is being worked on.
