### ISSUE TITLE
Getting CORS Issue

### ISSUE THREAD

**Issue by KarishmaSingh2301** [google/open-location-code#151]
Hi,
I am calling the api:
https://plus.codes/api?address=17.422066,78.338942&key=<api_key>
I have enabled GeoCodingAPI in developer console. While I am trrying to get the PlusCode for the above address, I am getting error: "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access."
Please suggest if I am doing anything wrong.
Thanks in advance.

**Comment by drinckes** [comment]
I retried it and I'm not getting the error - I tried from a browser and from a linux command line using CURL.

How are you making the request?

**Comment by KarishmaSingh2301** [comment]
This is an AngularJS application where I am using $http service. Code is as below:
      var apicall = 'https://plus.codes/api?address=' + latlang + '&ekey=' +Apikey;
                $http({
                    method: 'GET',
                    url: apicall,
                    headers: {
                        'Access-Control-Allow-Origin': '*',
                        'Access-Control-Allow-Methods': 'GET'
                    }
                }).success(function (response) {
                    $scope.Data = response.plus_code.global_code;
                }).error(function (qwe) {
                    var temp = qwe.statusText;
                });

**Comment by drinckes** [comment]
OK, I've added access-control-allow-origin headers to API responses. Please let me know if that fixes the problem!

**Comment by KarishmaSingh2301** [comment]
Hi @drinckes ,
Thanks for your quick response. The issue has been resolved now.
Great work.
I am closing the issue now.
Many many thanks again.

**Comment by drinckes** [comment]
No problem! Glad to help!
