### ISSUE TITLE
how can I determine locality names border?

### ISSUE THREAD

**Issue by benza86** [google/open-location-code#155]
how can I determine border of city (locality names) like: 
796QR7P7+:Lomba Tantum",
            "796QR7R7+:Palhal",

**Comment by bocops** [comment]
@benza86 There is no specific plus code for arbitrary shapes if that's what you're asking.

Every plus code corresponds to a near-rectangular surface area, the size of which depends on the precision of the plus code. An arbitrary shape like the area of a city could be defined by a collection of several plus codes, but there is no officially defined syntax for such a collection yet.
