### ISSUE TITLE
Converting pluscode to a long hash for internal usage

### ISSUE THREAD

**Issue by nyurik** [google/open-location-code#156]
I'm thinking of adapting plus codes for Elasticsearch, which already has [geohash_grid aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html).  Internally, it uses long integers to optimize data manipulation (in Java)  What would be a good way to convert plus codes to a long, given lat,long,and code precision?  Thx!

**Comment by bocops** [comment]
@nyurik Plus codes already are a numerical value in base-20, with the caveat that some of the positions can also be "0" to basically denote that we don't care about that level of precision. So, doing the following would be my first idea:

1. Input: valid OLC string
2. Remove '+' character and pad to fixed maximum length (for example 10) using '0' characters.
3. Consider that string to be a base-21, big-endian number using the code alphabet "023456789CFGHJMPQRVWX", where '0'=0 and 'X'=20.

Example: 5QG9RQHW+

--> 5QG9RQHW00
--> 0*21^0 + 0*21^1 + ... + 16*21^8 + 4*21^9
--> 3802856699943

What I currently can't quite wrap my head around is the fact that a plus code with a lower level of precision (say 6, 44XXXX00+) defines a map area that _contains_ all plus codes with the same prefix but higher precision (say, 44XXXX9R+ or 44XXXXQH+FV) - while the numerical value for that low-precision plus code would _precede_ all values of higher-precision plus codes inside of it.

I guess this might be exactly what tools like Elasticsearch are already taking care of, but it's still something to keep in mind.

**Comment by nyurik** [comment]
@bocops thanks for your suggestion!  I ended up implementing something very similar, just without the extra padding since the user already supplies the precision (grid cell size), making it a very convenient thing to reuse.  Check it out - https://github.com/elastic/elasticsearch/pull/30231/files?diff=unified#diff-108b0a96a65f3a2bc1a0443ae4242e0aR382

**Comment by bocops** [comment]
@nyurik Ah, so Elasticsearch only ever compares grid cells of the same precision? In that case, the padding is unnecessary, right. :)

**Comment by nyurik** [comment]
Right, within one search request the precision is constant.

**Comment by zongweil** [comment]
Closing this out as part of cleanup since it sounds like you found a way forward. Thanks for the reply @bocops!
