### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by tspoke** [google/open-location-code#164]
Hi,

I just wrote a typescript port of the JS version. I put it in my Github Account; I did some tests but I still need to add more tests (using your set of tests).

What's the procedure then ? Should I keep the code on my own repository or you prefer to move it here ?

Thanks.

Link to the repo : https://github.com/tspoke/typescript-open-location-code

**Comment by zongweil** [comment]
Hi! Thanks for reaching out. Since we don't have a Typescript implementation yet, we'd love to include it here (with attribution of course). Once you have passing tests, feel free to send a pull request.
