### ISSUE TITLE
Feature request : Polygone to Plus Code area

### ISSUE THREAD

**Issue by tspoke** [google/open-location-code#168]
Hi,

I'm looking for a feature, but I can't see it in any of the repository. I hope I missed it!

*Is there any implementation of the following problem ?* 
From a closed polygon (array of Point(lat, lon)), I would like to determine the list of all the plus code inside this polygon (area) with a specific precision (inclusive or exclusive).

Thanks !

**Comment by zongweil** [comment]
@bocops Is this something your [OpenGeoTile library](https://github.com/bocops/open-geotiling/blob/master/java/org/bocops/opengeotiling/OpenGeoTile.java) could support?

**Comment by bocops** [comment]
@zongweil Sounds very much like it, thanks for mentioning me. I'll be looking into that.

**Comment by bocops** [comment]
@tspoke I'm not yet completely happy with it, but I added this functionality to the "tile-area" branch of the repo @zongweil mentioned. Basically, you could now do:

    ArrayList<Coordinate> coordinates = ...; // list of coordinates goes here
    OpenGeoTile.TileSize tileSize = ...; // precision of resulting area
    TileArea area = new TileAreaPolygonalBuilder()
        .setTileSize(tileSize)
        .setCoordinatesList(coordinates)
        .build();

You can then retrieve all plus codes from the resulting TileArea.

There are still some issues with the code as is, I will add them to the issue tracker over the next few days - feel free to comment over there as well - but perhaps this already helps you a bit.

**Comment by tspoke** [comment]
Hi @bocops,

That's very cool ! Thank you a lot, I think it's a great feature :)
Give me some time to test your implementation, I will give you some feedback asap.
