### ISSUE TITLE
INVALID_REFERER for ekey without referer

### ISSUE THREAD

**Issue by mu10** [google/open-location-code#178]
I can't make request with ekey but without http referrer works.
It always returned INVALID_REFERER.

`{"error_message":"Needs Google API key to locate addresses","status":"NO_API_KEY","keyerror":"INVALID_REFERER"}`

On the wiki said, referrer is only needed for extra security.
 Is it become mandatory now?

PS: I also wonder if Plus Codes can actually requested directly via Google Geocoding API? 
Because I'm currently developing Android app now, but Geocoding response never has Plus Codes components.

**Comment by zongweil** [comment]
@drinckes to explain ekey/referrer behavior

Plus codes in the Geocoding API is being worked on right now! Doug, do we have an ETA we can share?

**Comment by drinckes** [comment]
Looks like there's a bug handling these requests. I'll look into it now.

**Comment by drinckes** [comment]
Hi @mu10 sorry about that, there was a bug in the processing of encrypted keys. I've fixed it and pushed an update to the live site, your requests should work now. Thanks for letting us know about it, let us know if it recurs.

As @zongweil mentioned, we're working on including plus codes in the normal Google APIs. It's already in the [Places API](https://developers.google.com/places/web-service/search), but we're still working on the Geocoding API. Once done we'll announce to the [mailing list](https://groups.google.com/forum/#!forum/open-location-code).
