### ISSUE TITLE
Trying to use Open Location Code with react-native

### ISSUE THREAD

**Issue by dsall** [google/open-location-code#179]
Hi guys, 
I am trying to use open-location-map with react-native. 
My react-native-app is created with expo, therefor i don't have access to the different android and ios folders in order to create some native methods using the Java version of open-location-code. 
I was trying to just use the Javascript version, but when i try to import it in any other javascript file it gives me some errors.  
I was trying to see if anyone have attempted this or has an idea on how to implement it.

**Comment by zongweil** [comment]
Hey @dsall,

What kind of errors does importing it give? Unfortunately, I don't think anyone's tried to use OLC in a React Native app before.

**Comment by dsall** [comment]
@zongweil  I was just trying to run it with m computer using node. I ended up getting some help from a friend and it worked. I am pretty sure that I can import it to my react native app and use it right now. 
I had to remove the "require('b')" on line 70 in the JS source file. After removing that it worked. I on't know how important that part of the code is. 

![image](https://user-images.githubusercontent.com/11328128/42491877-b582c4b0-83e4-11e8-967a-763c6a78b5ef.png)
![image](https://user-images.githubusercontent.com/11328128/42491882-c0dacb96-83e4-11e8-8377-3cbbb9f34ef3.png)
Then i just created a js file and imported the module. 

![image](https://user-images.githubusercontent.com/11328128/42491927-f5c5ba8c-83e4-11e8-910b-a26f84f3b830.png)

**Comment by zongweil** [comment]
Glad to hear it worked! Thanks for sharing your results.

I'm not too familiar with the JS implementation. Maybe @drinckes knows what that line does?

**Comment by drinckes** [comment]
From memory I think that chunk of code is designed to get it to work in both "plain" JS and Node.js. I'm not sure if I added it or it was contributed by someone else, but I'm not a Node.js expert.

**Comment by rjp44** [comment]
This issue is still live and needs fixing as far as I can tell. This lib still can't be imported into node or React environments without modification.

I'm pretty sure the chunk of code causing it is a bad copy-paste of some example code designed to be used when there is a dependency on the literal module name `b`. There is no external dependency here and a different, much simpler pattern is needed. Can contribute a fix.

**Comment by bocops** [comment]
The above seems correct. Searching for a one line of the comment above the failing line I found a ton of results, so this must be some sort of copypasta. Example: https://gist.github.com/CrocoDillon/9990078#file-memoize-js

Searching for the failing line itself, it seems to originate here: https://gist.github.com/jonschoning/5423962

@bilst I suggest to re-open and accept the fix by @rjp44, probably along the lines of the first example.

**Comment by bilst** [comment]
Thanks all for investigating. Happy to review a PR.
