### ISSUE TITLE
Add an internal max plus code length to all OLC implementations

### ISSUE THREAD

**Issue by zongweil** [google/open-location-code#190]
As discussed in [this thread](https://groups.google.com/forum/#!topic/open-location-code/mtnV1VF_K6k), we will internally process a max of 15 digits when encoding/decoding plus codes. This provides ~1cm x 0.5cm precision and will prevent the underflow errors mentioned in #12. 

Specifically, the following changes will be made:

- If you ask the library to encode a lat/long with more than 15 digits, the library will return a plus code with 15 digits.
- If you ask the library to decode a plus code with more than 15 digits, the library will only take the first 15 digits into account with the returned code area.
- Plus codes with more than 15 digits will be treated as **valid** if all the other validity constraints are satisfied. If the plus code has an invalid character after the 15th digit, it will be treated as **invalid**.

This issue tracks the work of updating all the OLC libraries.

**Comment by gonzus** [comment]
Maybe you want to reference PR #220 for the C implementation.

**Comment by WilliamDenniss** [comment]
#300 validates that this has been implemented in all languages (and fixes the last few remaining issues).

**Comment by zongweil** [comment]
Awesome! Marking this as closed.
