### ISSUE TITLE
the library in android

### ISSUE THREAD

**Issue by maqalaqil** [google/open-location-code#195]
how could i get the library in android i couldn't find it in the java folder

**Comment by zongweil** [comment]
We intentionally left the jar out, as we didn't want to maintain a jar there separately.

You can download the jar from [Maven Central](https://search.maven.org/artifact/com.google.openlocationcode/openlocationcode/1.0.0/jar) or even better, including it as part of your Gradle dependencies with the following line:

compile 'com.google.openlocationcode:openlocationcode:1.0.0'
