### ISSUE TITLE
Google Earth Doesn't Understand Plus Codes

### ISSUE THREAD

**Issue by CuriousJM** [google/open-location-code#222]
When I paste the Plus Code of a location, copied from Google Maps, into Google Earth Search I get an error "We couldn't understand this location".

I don't know whether it is Plus Code problem or GE problem. Taking it up with GE also

**Comment by CuriousJM** [comment]
Checked with Google Earth - The problem seems to be at their end. Hopefully it will be resolved soon.

**Comment by zongweil** [comment]
Thanks for following up with Google Earth! I'm going to close this issue since it doesn't seem to be on our end. Feel free to re-open if that changes.

**Comment by drinckes** [comment]
There's two versions of Google Earth - the one on android/mobile/chrome, and Earth Pro on Desktop.

There was a problem in Google Earth Pro, but it's **just** been fixed. If you go to https://www.google.com/earth/desktop/ and download the latest version, plus code searches in Google Earth should be working.
