### ISSUE TITLE
MapCode vs Plus Code?

### ISSUE THREAD

**Issue by teamcoltra** [google/open-location-code#223]
Looking at your list of different systems, I notice no actual flaws in your analysis of MapCode and am curious the decision to come up with a new system instead of supporting the existing one that matches your requirements?  or did I miss something?

**Comment by bocops** [comment]
There are quite a few issues being mentioned for MapCodes:
- "a data file needs to be maintained and distributed"
- "cannot be truncated"
- "single location can have multiple different codes"
- "challenges distinguishing visually similar codes" [in non-latin character sets]

https://github.com/google/open-location-code/wiki/Evaluation-of-Location-Encoding-Systems

**Comment by Masturedehghanipoor** [comment]
Hello my friend
Please turn Off this post for me
Tanks

**Comment by drinckes** [comment]
The big issue for me was that one place has multiple, wildly different references, since that would seem to be guaranteed to lead to confusion:

> A single location can have multiple different codes. For example, Schiphol Airport in Amsterdam has the code (without a territory identifier) "VHWK5.G7YB", and codes (with territory identifiers) "NLD 8G.262", "NLD DCC.J5H", and "NLD N3V5.4PZ".
