### ISSUE TITLE
Hierarchical Sphere Pixelization

### ISSUE THREAD

**Issue by jankotek** [google/open-location-code#23]
There is entire category of spherical location codes used in astronomy. Compared to Lat/Long codes it does not have distortion and requires shorter code.  

Not sure if this is useful, just FYI

http://healpix.jpl.nasa.gov/

http://research.microsoft.com/pubs/64531/tr-2005-123.pdf

http://www.skyserver.org/htm/

http://www.sai.msu.su/~megera/oddmuse/index.cgi/SkyPixelization

http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1992ASPC...25..379W&db_key=AST

![img](http://healpix.jpl.nasa.gov/images/healpixGridRefinement.jpg)

**Comment by waldyrious** [comment]
You should probably try to integrate this information into the [project's wiki](https://github.com/google/open-location-code/blob/master/docs/comparison.adoc] :)

**Comment by waldyrious** [comment]
@drinckes any words on why this was closed?

**Comment by drinckes** [comment]
I thought it can still be done if someone wants, but I can see closing the issue gave the wrong impression. Sorry.

I'll open it and leave it with a help wanted tag. If someone wants to do it, they can pick it up.

**Comment by drinckes** [comment]
I don't think it's appropriate to add this content to the comparison doc, since that would give the misleading impression that this category was evaluated prior to the design of OLC.

With that in mind, I'm going to close off this issue.
