### ISSUE TITLE
Rubbersheet and shifting plate tectonics

### ISSUE THREAD

**Issue by a-raccoon** [google/open-location-code#235]
I realize OLC has been around for a couple years now, but this is a matter that affects all lat-lon coordinate systems and should eventually be addressed by somebody.  I figure I'll expound my grievances here.

While it was not explicitly mentioned in the Desired Attributes list, there was one attribute that was implicitly sought to be avoided, as reasoned by this statement:  "[A]nd multiple different codes can decode to the same value," which appears to be denoted as a negative feature of Geohash.  However, in order to compensate for plate tectonics and rubber mat issues in mapping, we are going to have to accept multiple codes that translate to the same region or point center.

A design that would better allow for plotting of points on a fluid and evolving surface as that of Earth's, would be one that identifies one of several shifting point-centers and then plots an angle and distance from that point radiating outward.  Your starter points would be coarsely and arbitrarily defined, equally spaced on the globe to start, but then eventually ingrained into the public conscience as fixed and real tectonic surface locations pegged to a physical stake inserted into the soil... slowly moving with the currents of liquid dirt.

The reason why we will eventually need a coordinate system like this is if we're ever going to associate a fixed point to a fixed spot, instead of continually assigning real locations with new, updated, coordinates every so often.  It's a very real problem, because it's not just the singular motion of a single plate in a single direction that throws everything off, but the compounded summation of multiple plates moving in multiple directions that may move a monument or city from point A to new point B.

By devising a system where you start at a stake-in-the-ground point, angles and distances from that stake should remain fairly constant for thousands or millions of years to come, but more importantly, can identify the same spot that existed thousands and millions of years in our historic past (assuming that reference point was geologically local).  I imagine such a system would become immediately useful to archaeologists, anthropologists and paleontologists, if not future historians trying to locate the Lost City of Zurich.

But also in dealing with faulty and corrected satellite imagery overlays and rubbersheet cartography.

FYI, there are cities around the world that move inches every 10 years, perhaps feet back when liquor was banned, or several meters (or yards? or ells? or amahs?) back in biblical times.

**Comment by drinckes** [comment]
Thanks - we did think about this and eventually decided that the small rate of movement was acceptable within the likely lifespan of a street address.

We were very careful to scope plus codes as a solution to street addressing. If you want references that are fixed over archaeological time scales, that's going to require a whole other approach - presumably it wouldn't be able to rely on GNSS signals either?
