### ISSUE TITLE
TransactSQL implementation

### ISSUE THREAD

**Issue by victorvartan** [google/open-location-code#236]
Hi everybody! 

I wrote a TransactSQL function to encode Open Location Codes from latitude and longitude pairs directly in the database.
I only added the encoding part for now, as I think it's the most important, and when I'll have some time I want to do the same for the others (shorten, extend, test etc.). 

Here's the link to the repo: https://github.com/victorvartan/OpenLocationCode-TransactSQL

Hope it helps!

**Comment by zongweil** [comment]
Thanks for sharing Victor!
