### ISSUE TITLE
Convert the JS code to work with node.

### ISSUE THREAD

**Issue by nolim1t** [google/open-location-code#24]
I think its a good project that appeals with the travelling demographic as not all places actually have addresses.

Though would be good to get as many libraries up for this. Would love to see the JS code usable in node.js though (ideally as something you can install with npm)

Thoughts?

**Comment by drinckes** [comment]
I'm open to it but don't know anything about node.js so I can't make any commitment. If anyone else wants to pick this up, feel welcome.

**Comment by drinckes** [comment]
I'm playing with adding a package file to the existing JS, so that the tests can be executed on travis-ci.org using npm (and qunit and a bunch of other stuff). But I don't know if this is sufficient or if changes are needed to the openlocationcode.js file?

**Comment by bernharduw** [comment]
To equally support node.js, browser globals and module loaders using AMD (such as require.js), you can wrap the function in openlocationcode.js in an [UMD definition](https://github.com/umdjs/umd). I think the most suitable variant would be [returnExportsGlobal](https://github.com/umdjs/umd/blob/master/returnExportsGlobal.js).
If you want, I can create a pull request for this.
