### ISSUE TITLE
Google search fails for plus codes

### ISSUE THREAD

**Issue by fulldecent** [google/open-location-code#243]
# Test case

1. Generate a valid plus code 
2. Search in Google search

# Expected outcome

Search result shows location. This specification is advertised at https://plus.codes/developers: 

> Thanks to the plus symbol in each code, they are easy to identify (in Google search, for example). **The plus symbol also allows to correctly interpret partial plus codes.** [Emphasis added]

# Actual outcome

Search result does not show location.
 
<img width="1158" alt="screen shot 2018-11-29 at 10 13 12 am" src="https://user-images.githubusercontent.com/382183/49231195-6e527180-f3bf-11e8-886b-9f29857f15e9.png">

# Discussion

Here is a plus code for a place:

> 4WCH+97 Huntingdon Valley, Bryn Athyn, PA

<img width="1158" alt="screen shot 2018-11-29 at 10 13 20 am" src="https://user-images.githubusercontent.com/382183/49231187-6b578100-f3bf-11e8-929b-fa5eacb9aa7e.png">

I tried searching for that on Google using various formats. My computer is close to this location, no VPN. Here are the results:

* ✅ 4WCH+97 Huntingdon Valley, Bryn Athyn, PA
* ✅ 4WCH+97
* ❌ 4WCH+

I was expecting 4WCH+ to present a map on Google.com search results but it did not:

---

Using https://plus.codes I can confirm that this is a valid code. It will NOT work if you paste it into the search box at https://plus.codes but it WILL work if you use https://plus.codes/87G64WCH+ then zoom into somewhere near me and then search.

This confirms that it is a valid plus code.

<img width="1158" alt="screen shot 2018-11-29 at 10 14 52 am" src="https://user-images.githubusercontent.com/382183/49231297-a78ae180-f3bf-11e8-8f9a-6eeaf2073deb.png">

**Comment by drinckes** [comment]
Google searches only support codes of at least 10 digits (that is, two digits after the +). You can do a search for a shorter code in Google Earth, but it must be a global code ("8FVC4WCH+") not an address ("4WCH+ Zurich, CH" does not work).

Currently our focus is on supporting searches at an address level, not at this larger level. If you can explain your use case we can use that to prioritise additional support.

**Comment by fulldecent** [comment]
Thank you. Now that I understand the position, I believe the discrepancy can be resolved by editing

https://plus.codes/developers

to state: 

> Thanks to the plus symbol in each code, they are easy to identify. The plus symbol also allows to correctly interpret partial plus codes. Google search supports some plus codes.

If https://plus.codes/developers is on GitHub then I can send a PR.

**Comment by drinckes** [comment]
Source for the website is not on GitHub but I'll look into the change in our next refresh.

**Comment by fulldecent** [comment]
Thanks for looking into this.
