### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by dantaya** [google/open-location-code#253]
I havn't been able to find this anywhere.

Is there any way to get all plus codes within 10 meters of a given one?

EX: I have a database of plus codes. I have a users location lat/lng. I need to query the db to get all records within 10 meters of the user.

Or would it be easier to query all lat/lngs in the radius? (in which, using pluscodes becomes almost useless for my application)

Thanks in advance.

**Comment by bocops** [comment]
@dantaya That depends on how exact you need that "within 10 meters" part to be fulfilled.

1. Each plus code defines an area, the size of which depends on the length of the code (and your position on the globe, areas get smaller towards the poles). A plus code of length 10 ("XXXXXXXX+XX") defines an area of 0.000125° x 0.000125°, which means a side length of up to 14 meters.
2. Longer codes define a smaller area, but have a longer code as their prefix ("XXXXXXXX+XXY").

This means that you could generate a 10-digit code for a location, then find the 8 neighboring codes of the same length, then query your db for all entries where those codes are the prefix. Some of these entries might have a distance to your location of slightly more than 10 meters - but if ~30 meters is still good enough, that would probably be the easiest solution.

11-digit codes define an area of 3.5m x 3.5m, so if you need to be more precise, you could use those and do a sort of flood fill from your location to the max distance you want to allow.

**Comment by dantaya** [comment]
ok, so as I thought, I would have to pragmatically find all the codes that fit in the radius then query for them. As where with coords, I can query the radius directly from the db. 

Your answer perfectly fit what I was looking for thanks!
