### ISSUE TITLE
[olc_definition.adoc] - 11 digit's approximate area size

### ISSUE THREAD

**Issue by 365ejk** [google/open-location-code#254]
There is kind of confusing statement in [olc_definition.adoc] regarding 11 digits area size.

Two statements:
"roughly 3.4 by 2.7 meters" vs "2.6m x 2.8m"

In context:
"we have an 11 digit code that represents a 1/32000° by 1/40000° area (roughly 3.4 by 2.7 meters)."
"A 10 digit code divided into its grid. Each small square is approximately 2.6m x 2.8m .."

It is confusing which is the real size for 11 digit code area.
Help!

**Comment by bocops** [comment]
The size of the area represented by an 11-digit code changes with its position on the globe. This has to do with the longitude convergence you asked about in a separate issue.

A paragraph before, the side length of a 10-digit code area near the equator is given as 13.9 by 13.9 meters. Divide that by 4 or 5 respectively, and you'll get an area of 3.4[75] by 2.7[8] meters.

Towards the poles, the first value shrinks while the second stays constant, so there will be some location where the area of an 11-digit code has the size (rounded) of 2.6 by 2.8 meters.

So, both numbers are correct, but this could in fact be clarified in the doc.

**Comment by drinckes** [comment]
Good catch, thanks for spotting this. I'll take an action to update the documentation.

**Comment by drinckes** [comment]
Aaaaand the next thing I see is that @bocops has sent a fix. :+1:

**Comment by malleo** [comment]
I found in the open location code definition and in several posts that (at the equator) the size of a given OLC area is equal in both width and height.
This is not what I find in the following examples:

Equator: circumference 40000 km (logitudinal range 360 deg/ latitudinal 180 deg)
Digit  1-2: Lon: 2000 km / Lat: 1000 km Lon: 18.0 deg       / Lat: 9.0 deg
Digit  3-4: Lon:  100 km / Lat:   50 km Lon:   .9 deg       / Lat:  .45 deg
Digit  5-6: Lon:    5 km / Lat:  2.5 km Lon:   .045 deg     / Lat:  .0225 deg
Digit  7-8: Lon:  250 m  / Lat:  125 m  Lon:   .00225 deg   / Lat:  .001125 deg
Digit 9-10: Lon: 12.5 m  / Lat: 6.25 m  Lon:   .0001125 deg / Lat:  .00005625 deg
Digit   11: Lon: 3.125 m  / Lat: 1.25 m  Lon: .000028125 deg / Lat: .00001125 deg
Digit   12: Lon: .78125 m  / Lat: .25 m  Lon: .00000703125 deg / Lat: .00000225 deg

Lat: 52 deg: (~Hannover/germany) circumference 24626 km
Digit  1-2: Lon: 1231 km / Lat: 1000 km Lon: 18.0 deg       / Lat: 9.0 deg
Digit  3-4: Lon:   62 km / Lat:   50 km Lon:   .9 deg       / Lat:  .45 deg
Digit  5-6: Lon:  3.1 km / Lat:  2.5 km Lon:   .045 deg     / Lat:  .0225 deg
Digit  7-8: Lon:  150 m  / Lat:  125 m  Lon:   .00225 deg   / Lat:  .001125 deg
Digit 9-10: Lon:  7.7 m  / Lat: 6.25 m  Lon:   .0001125 deg / Lat:  .00005625 deg
Digit   11: Lon: 1.92 m  / Lat: 1.25 m  Lon:   .000028125 deg / Lat: 00001125 deg
Digit   12: Lon:  .48 m  / Lat:  .25 m  Lon:   .00000703125 deg / Lat:.00000225 deg

Lat: 78 deg: (Spitzbergen/svalbard) circumference 8316 km
Digit  1-2: Lon:  416 km / Lat: 1000 km Lon: 18.0 deg       / Lat: 9.0 deg
Digit  3-4: Lon:   21 km / Lat:   50 km Lon:   .9 deg       / Lat:  .45 deg
Digit  5-6: Lon:    1 km / Lat:  2.5 km Lon:   .045 deg     / Lat:  .0225 deg
Digit  7-8: Lon:   52 m  / Lat:  125 m  Lon:   .00225 deg   / Lat:  .001125 deg
Digit 9-10: Lon:  2.6 m  / Lat: 6.25 m  Lon:   .0001125 deg / Lat:  .00005625 deg
Digit   11: Lon:  .65 m  / Lat: 1.25 m  Lon:   .000028125 deg / Lat: 00001125 deg
Digit   12: Lon:  .16 m  / Lat:  .25 m  Lon:   .00000703125 deg / Lat:.00000225 deg

So where is my mistake?

**Comment by drinckes** [comment]
Hi @malleo,

A two digit code is 20 degrees by 20 degrees.
A four digit code is 1 degree by 1 degree.

I'm not sure where you're getting your measurements? Could you post your example codes and let us know what software library you're using?

**Comment by malleo** [comment]
Hi @drinckes,
My calculations were simple divisions by 20 for the first 10 digits based on the equatorial circumference of the earth (~40000km) and a full circle of 360 degrees for longitude and a half circle (180 degrees) for latitude. For the the 11th and 12th digit I divided the results for the 10th resp. 11th digit by 4 for longitude and by 5 for latitude.
If I sum up the 20 degrees for a 2 digit OLC 20 times it results in 400 degrees for a full circle. Is that what it should be?

**Comment by bocops** [comment]
@malleo The first two digits don't use all of the available OLC characters, but just 18 (x20=360) or 9 (x20=180), respectively.

**Comment by zongweil** [comment]
Closing this as @bocops clarified the docs.
