### ISSUE TITLE
contact page outdated

### ISSUE THREAD

**Issue by justinelliotmeyers** [google/open-location-code#257]
https://plus.codes/discuss

email here bounced back; is this e-mail working?
open‑location‑code@googlegroups.com

Thanks!
Justin

**Comment by zongweil** [comment]
You have to be a member of the Google group in order to post (anyone can join). See https://groups.google.com/forum/#!forum/open-location-code. Try joining and emailing again :).

**Comment by G00FTR00P9D** [comment]
Wats up
