### ISSUE TITLE
Under the Woods Event Center: incorrect plus code

### ISSUE THREAD

**Issue by karaunderwood** [google/open-location-code#260]
Hi, the plus code on my google business is completely wrong. Its taking people about 5 miles from my business. My address is correct but the plus code is wrong. How do I get this fixed??

Under the Woods Event Center
20121 US-71, Jane, MO 64856

**Comment by bocops** [comment]
Plus codes are "just" a different form of writing down a set of coordinates. If the pin on Google Maps is correct, then the plus code should be correct as well.

In fact, when searching on Google Maps for "Under the Woods Event Center", a pin appears between Highway 71 and Tate Road, in the same location that is also used by the Maps widget on your web site, and when searching for the plus code of your Maps entry here: https://plus.codes/8687GPC4+P4. This doesn't seem to be an issue with the plus code specifically.

If you are the owner of that Maps entry, you might be able to change the exact location via your MyBusiness entry - not sure if that still is a thing. If not, you should be able to search for your business on Google Maps, then "Suggest an edit", "Change name or other details", "Update location on the map" to move the map pin to a different location.

**Comment by PatsyClark** [comment]
Call me and I will explain it to you. I will move the location of your Google business listing flag.   Do you have access to your Google business platform you can do it also.  Google plus codes take the location of your flag.  I’m happy to help. Call me

Patsy Clark
Snap Realty
DBA/ Snap It Up Location Data Management 
www.SnapItUp.Tech
919-971-7030

See what I've posted to Google Maps
Level 8 Local Guide 
https://goo.gl/maps/CSYkKPFhhNz

Google Business Listings and MLS Listings with GPS 📍 Embedded  💫 360° ©️Photography Integrated with your Google and Google Business Listing That Disseminates to All Map and Business Platform  🧭

Licensed, Bonded and Insured
A Division of Snap Realty 
Snap Realty, LLC
Principal Real Estate Broker & Owner

**Comment by drinckes** [comment]
Closing because as others have mentioned your listing on Google Maps looks like it's not at your actual location.
