### ISSUE TITLE
Add a new service to Who supports OLC? wiki page

### ISSUE THREAD

**Issue by canerbasaran** [google/open-location-code#279]
[nicesi.com](https://nicesi.com) (early 2019) Nicesi Location API support for global codes in [reverse geocoding service](https://nicesi.com/doc/#reverse-geocoding)

**Comment by zongweil** [comment]
Would you mind making a pull request with the change to the wiki?

**Comment by canerbasaran** [comment]
I didn't find wiki pages in the repo.

**Comment by zongweil** [comment]
I think you can update this page directly - https://github.com/google/open-location-code/wiki/Who-supports-OLC%3F

**Comment by canerbasaran** [comment]
It shouldn't be that hard. https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by zongweil** [comment]
Can you edit that page I linked directly? I don't think you need to send a PR to update it.

**Comment by canerbasaran** [comment]
I couldn't. There is no edit button in that page.

**Comment by zongweil** [comment]
I manually added it. Thanks for supporting plus codes!
