### ISSUE TITLE
Fix floating point precision for Rust implementation

### ISSUE THREAD

**Issue by zongweil** [google/open-location-code#317]
See #307 for details. This issue tracks the fix for the Rust implementation.

**Comment by sergey-melnychuk** [comment]
Looking into it.

**Comment by drinckes** [comment]
Hi @sergey-melnychuk ! Thanks for offering to help!

The fix is to implement a new algorithm for the encode() and decode() methods.

The Go implementation (in this repo) has already been updated, so you can copy from there. Let me know if you have any questions!
