### ISSUE TITLE
Link to this repo on plus.codes is incorrect

### ISSUE THREAD

**Issue by danrademacher** [google/open-location-code#33]
Links to gthub*.org*. Should be *.com*. I don't see that code in this repo, but would be nice if the owner of the demo site could fix that link.

**Comment by morciej** [comment]
NOT corrected yet. Link in plus.codes Help sidebar is https://plus.codes/github.com/google/open-location-code, goes nowhere. Should be https://github.com/google/open-location-code

**Comment by drinckes** [comment]
Good catch, obviously I fixed .org and broke the link entirely. Should be ok now.
