### ISSUE TITLE
js implementation and Internet Explorer

### ISSUE THREAD

**Issue by qgillet** [google/open-location-code#339]
Because of the use of exponentiation (**) in the js implementation, the js library cannot work in Internet Explorer. IE is the only browser that does not support exponentiation.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Browser_compatibility

**Comment by zongweil** [comment]
Thanks for the heads up! @drinckes we might have to use something like Math.pow instead.

**Comment by zongweil** [comment]
@drinckes fixed this, thanks again for bringing this to our attention @qgillet!

**Comment by qgillet** [comment]
Thank you for your swift fix! I confirm that the js library is now OK in Internet Explorer 11.
(I tested the encode function).

**Comment by drinckes** [comment]
Awesome! Thanks for the issue report!
