### ISSUE TITLE
Conflict in API and definition

### ISSUE THREAD

**Issue by famer** [google/open-location-code#35]
Formatting section in https://github.com/google/open-location-code/blob/master/docs/olc_definition.adoc
conflicts with API definition for `isValid` function in https://github.com/google/open-location-code/blob/master/API.txt in following:

> Formatting: The solution here is to use zero, as a padding symbol, giving us 6GCR0000+.  

>  isValid: If the separator character is present, it must be after four characters.

**Comment by drinckes** [comment]
Thanks. Updated in pull request #41 .
