### ISSUE TITLE
short codes for larger areas?

### ISSUE THREAD

**Issue by petjal** [google/open-location-code#352]
Low priority.

![image](https://user-images.githubusercontent.com/3526136/58984289-b1decb80-87a6-11e9-8f56-d15bf035bd01.png)

I'm new, probably missing something, but maybe it would be nice to be able to link to or describe the greater Boston area with something like?:
https://plus.codes/87JC+
Or the North Shore with like 
https://plus.codes/87JF+

See: https://github.com/google/open-location-code/wiki/Guidance-for-shortening-codes

**Comment by zongweil** [comment]
@drinckes WDYT about the ability for the libraries to parse codes with <8 digits? I believe they will fail the isValid check right now if they don't have the "+" separator.

**Comment by bocops** [comment]
@petjal This is possible, but there need to be eight characters in front of the plus sign. For a bigger area you can use zeroes to fill up: https://plus.codes/87JC0000+

**Comment by petjal** [comment]
**Exactly** what I was looking for!  Thanks!

**Comment by petjal** [comment]
![image](https://user-images.githubusercontent.com/3526136/58998460-d353ad80-87ce-11e9-8215-00e06327a621.png)
Nice!
