### ISSUE TITLE
spelling error on website

### ISSUE THREAD

**Issue by evelynmitchell** [google/open-location-code#36]
The codes aren't case sensitive and don't include easily confused characters. We've selected the characters to make it difficult to impossible to spell words in any language.

should be

The codes aren't case sensitive and don't include easily confused characters. We've selected the characters to make it difficult to impossible to misspell words in any language.

**Comment by waldyrious** [comment]
That's not a typo: the idea is that real words from a language should not be formed (correctly spelled) accidentally by an OLC.

**Comment by drinckes** [comment]
What he said. ;-)
