### ISSUE TITLE
https://drive.google.com/file/d/0B__A3WelbVrsM1piSjZwd000anZ5bWFheVpjMmFSbEFHTHhz/view?usp=drivesdk

### ISSUE THREAD

**Issue by krisRam432** [google/open-location-code#363]
Alex Flores

**Comment by torfason** [comment]
What is this issue, is it a malware link? I'd rather not open the file that is referenced in the title. Unless there is something here that I'm totally misunderstanding it seems like this should be closed ...

**Comment by Tinar58** [comment]
What this

**Comment by krisRam432** [comment]
#25 #551 #495
