### ISSUE TITLE
Please review fragment that seems false assertion at Wiki

### ISSUE THREAD

**Issue by ppKrauss** [google/open-location-code#375]
Hi, seems a **false assertion** [at this wiki article](https://github.com/google/open-location-code/wiki/Evaluation-of-Location-Encoding-Systems#geohash) ([since 2018 or before](https://web.archive.org/web/20180213140209/https://github.com/google/open-location-code/wiki/Evaluation-of-Location-Encoding-Systems)),

> A single location can have more than one code, depending on the input values, and multiple different codes can decode to the same value. For example, "c216ne4" and "c216new" (and others) all decode to the same coordinates (45.37 -121.7).

Use [reliable Geohash software](https://mmcloughlin.com/posts/geohash-assembly) or reliable online implementation, like [movable-type.co.uk/geohash](https://www.movable-type.co.uk/scripts/geohash.html):<br/> `c216ne4`="45.3687,-121.7031" and `c216new`="45.3715,-121.6976".<br/>  There are no *"multiple different codes decoding to the same value"*, it is false. The precision of the centroid is not a function of the Geohash area.  It is compliant with [Geo URI standard](https://en.wikipedia.org/wiki/Geo_URI_scheme), 

> The number of digits of the values in &lt;coordinates&gt;  MUST NOT be   interpreted as an indication to the level of uncertainty <br/>https://tools.ietf.org/html/rfc5870#section-3.4.3

The only valid conversion/inference  is between *Geohash area* and it centroid's *location uncertainty*, used as Geo URI. Same interpretation is valid also for OLC area.

**Comment by fulldecent** [comment]
At a minimum, our wiki has a broken link. `c216ne4` is not valid on http://geohash.org

<img width="1446" alt="Screen Shot 2021-04-25 at 00 32 59" src="https://user-images.githubusercontent.com/382183/115980854-d9d3a580-a55d-11eb-92e0-f669d3a4b0b6.png">

**Comment by drinckes** [comment]
Look like the geohash.org implementation is invalid - it rejects `c216ne4`, and decodes `c216ne` and `c216new` to the same lat/lng.

I'll update the wiki.
