### ISSUE TITLE
Go : why second normalization ?

### ISSUE THREAD

**Issue by kpym** [google/open-location-code#376]
In [encode.go](https://github.com/google/open-location-code/blob/a6eb95b4d2f934e94dae4f092260caf7f3db7967/go/encode.go) it looks like the longitude is normalized twice : 
- on [lines 56](https://github.com/google/open-location-code/blob/a6eb95b4d2f934e94dae4f092260caf7f3db7967/go/encode.go#L56)
- and on [lines 63-65](https://github.com/google/open-location-code/blob/a6eb95b4d2f934e94dae4f092260caf7f3db7967/go/encode.go#L63-L65)

Is this normal ?

**Comment by zongweil** [comment]
Thanks for bringing this up @kpym. You're right that the second normalization check is unnecessary, since lng will never equal lngMax after the first normalizeLongitude() call. 

Feel free to send a PR if you'd like :). Otherwise, I can fix it later.
