### ISSUE TITLE
Wrong Suburb

### ISSUE THREAD

**Issue by magneticimpulse** [google/open-location-code#377]
Wrong suburb, it is not Northside in the address. Need to be removed from all Suburbs in Dublin, Ireland and addresses.

**Comment by drinckes** [comment]
Hi @magneticimpulse - these issues are for problems with the open source code.

If you are providing feedback for a plus code address on a specific mapping app, please use their feedback mechanism (e.g. if it's an issue on Google Maps, use Menu then Help&Feedback). If you do, it would be helpful if you could include the full plus code and a screenshot.

I'm going to close the other issues, but I'll add comments where I can.

**Comment by magneticimpulse** [comment]
hi i am not computer oriented. i dont know where the original source for the plus code comes from but it is incorrect. multiple times over 2 years i have contacted google maps to change it and they did not. i noticed a plus code attached with the incorrect address. plus code told me to come here to get it fixed. im not a computer person...i dont know how to rewrite the code. nobody will fix the surburb address where i live and the whole of the northside of Dublin addresses are wrong and google maps is based in Dublin and they cannot even get the address in their home city correct. what can i do to get the right person to fix it?

**Comment by bocops** [comment]
@magneticimpulse If I understand you correctly, you are saying that, in a plus code like **8PXF+93 Dublin 7, Northside, Dublin, Ireland**, the part "Northside" is not correct and needs to be dropped completely - no replacement necessary?

@drinckes If that is the case, this seems to be an issue with the way short codes are generated, rather than with Maps in general. I'm looking at a Google Maps POI with the ID "ChIJs0Ciwy4MZ0gRFFpl7MaNZAQ" (Jameson Distillery Bow St) right now, and while that POI uses the "Northside" string in its short code, most of the neighboring POIs even in the same street do not contain that string.

**Comment by magneticimpulse** [comment]
Yes exactly. some places in Dublin have the word "Northside" instead of their proper Townland/suburb name which is incorrect. how do i get it fix? i know nothing about computers or how these plus codes are generated or who to contact to fix the code/address. do you know who or when i can apply to get it fixed?

**Comment by bocops** [comment]
@magneticimpulse I suggest that you explain this in a post on this forum: https://groups.google.com/forum/#!forum/open-location-code

**Comment by magneticimpulse** [comment]
the name Northside doesnt just need to be dropped. the correct suburbs need to be placed. ive contacted google maps to change the address and they must be simple people working at goolge because its not fixed. i dont see how a forum can help me because anything they suggest is not going to automatically fix the address. where are the codes stored??? why will nobody fix it for me?? surely this is where all the coders come to fix it?

**Comment by drinckes** [comment]
I'll pass this on to the right team (I work for Google).

**Comment by magneticimpulse** [comment]
thanks i tried to add a comment to the post but dont know how i do from a mobile phone. Many of the plus codes still need to be updated.
Some have the correct suburb now added (others still need the suburb added). the following plus code needs Northside to be removed and County Needs to he removed. the plus code should say "Finglas, Dublin 11" and not the following for 9PQ2+W6 Finglas, Northside, County Dublin

**Comment by magneticimpulse** [comment]
Any update on this? I checked Google maps and the edits to my address which i requested to be corrected and it still comes up as pending review. The area of Finglas is still coming up as "Northside" and my busstop in Finglas village is still coming up as "Glasnevin". ive requested the corrections to be made. this is very poor given that google maps Headquarters is in Dublin and the addresses and suburbs in Dublin are wrong after requesting corrections for at least the past 2 years.

**Comment by magneticimpulse** [comment]
Nothing has been done to fix this issue. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment]
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment]
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment]
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment]
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment]
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode D11Y1E2!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment]
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode D11Y1E2!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.
