### ISSUE TITLE
I'll tar and feather someone if the Parish system ever comes to Texas! 

### ISSUE THREAD

**Issue by TexasMongoloid** [google/open-location-code#386]
There is not a single Parish style of government outside of Louisiana. Port Arthur has quite a few problems, but being governed by a Parish is not 1 of them. 

W2R4+PP Port Arthur, Parish Governing Authority District 1, TX

**Comment by drinckes** [comment]
Google Maps had an issue rendering addresses where parish or county names were being included in addresses. This should be resolved now.
