### ISSUE TITLE
Less Accurate Location Code

### ISSUE THREAD

**Issue by alextechtai** [google/open-location-code#387]
Is there a way to broaden/obscure a given location?

**Comment by zongweil** [comment]
Codes with fewer digits represent a larger area. For example, [87G7MXQ4+M5](https://plus.codes/87G7MXQ4+M5) is the full code for the Statue of Liberty in New York. Shortening it to 87G7MXQ4 will represent a large rectangle that is centered at the same point (doesn't look like the plus.codes UI will let you do this directly though).

What's your use case? If you want to obscure the location a bit, you could theoretically pick a random neighbor.

**Comment by bocops** [comment]
To add to what @zongweil said, shortening is possible even beyond eight digits, by replacing pairs of digits with '0':
87G7MX00+
87G70000+
87000000+

**Comment by alextechtai** [comment]
Hey, my use case is I want to be able to get user location and obscure it before encrypting it and storing it onto a database

**Comment by alextechtai** [comment]
@zongweil Hey, my use case is I want to be able to get user location and obscure it before encrypting it and storing it onto a database

**Comment by alextechtai** [comment]
@bocops That's really helpful! Do they have documentation for doing so?

**Comment by bocops** [comment]
@alextechtai This is mentioned as "padding" in
- [https://github.com/google/open-location-code/blob/master/docs/olc_definition.adoc](url) and
- [https://github.com/google/open-location-code/blob/master/docs/specification.md](url)
