### ISSUE TITLE
VJQ7+VV is wrongly named, should be corrected to "PARIWAR PALACE APARTMENTS".

### ISSUE THREAD

**Issue by harshg1971** [google/open-location-code#390]
We are a happily living community at the following code, which has more than 100 apartments and a few shops. We had named this as "PARIWAR PALACE APARTMENTS" for years and using this as an address.
Apparently one of the shopkeepers has claimed this as a business, depriving more than 100 families the benefit of sharing their location easily on maps.

VJQ7+VV Devarachikkana Halli, Bengaluru, Karnataka, India

We have requested this already multiple times at google maps, but of no use. Please suggest a way for us to reclaim or else create one more plus code for this.

**Comment by bocops** [comment]
A plus code is just a different way of communicating a specific location. Just like no one can claim the coordinates **12°53'23"N 77°36'53"E**, no one can claim a plus code.

What probably happens is that the business has an entry on Google Maps in this location, leading to Maps displaying the plus code that best fits the location of the business. That doesn't mean that the same plus code can not be used for other purposes at the same time.

If **VJQ7+VV Devarachikkana Halli** is a good plus code to describe the entrance to your apartment building, why can't you just continue to use it that way?

**Comment by harshg1971** [comment]
Maybe then i expressed the concern wrongly. For not so tech savvy people (100+ families), we want the default display of address as "PARIWAR PALACEAPARTMENTS"

**Comment by zongweil** [comment]
Hey @harshg1971, it sounds like you might need to create a [Google My Business](https://www.google.com/business/) account for Pariwar Palace Apartments. That's how the business names show up on Google Maps. 

If someone in your complex already created a GMB account with that plus code, you may need to contact GMB support to help you out. Either way, this isn't an issue with plus codes.

Hope this helps!

**Comment by gpkulkarni** [comment]
Google,
This is affecting my google search for my friends and relatives.
when they search Pariwar Palace apartment, it is not showing previously it was showing.
Can please fix this simple fu**ing issue/bug instead of giving gyan!!

**Comment by drinckes** [comment]
If you have an issue with data on Google Maps, you have to report it using Google Maps feedback. We can make suggestions but nobody in this project is able to fix your issue.

Any further abuse will result in you being blocked from this repository.

**Comment by gpkulkarni** [comment]
I was thinking this is the project from google/partnered to manage the location updates.
It is almost a year now, we are reporting the problem,  and still it is not fixed. Can you please point me to right forum where we can share our concern. There are 120 families and every one has google gmail, android phone youtube... and is this not the enough busyness for google as compared to GMB. How come google rename it just because someone paid for it?

**Comment by cipri-tom** [comment]
@gpkulkarni this project is about technical implementation of converting between longitude and latitude to a different format. There is a reference above for updating data in maps, through GMB. 

I'm afraid this project cannot help you with your request, as it does not manage google data in any way. For example, I have nothing to do with google, yet I am using this implementation for a project of mine.

Please try to contact google maps directly.
