### ISSUE TITLE
Find adjacent blocks

### ISSUE THREAD

**Issue by floyernick** [google/open-location-code#394]
Hello! I'm curious is there an algorithm to find adjacent blocks to the chosen one? For example, if I pick 9G28, I need to find blocks 9G27, 9G29, 9G37, and 6 more blocks that surround picked one. Thanks.

**Comment by bocops** [comment]
The easiest would be to get the underlying lat/long of a plus code, then add/subtract a constant value for that block size, then create new codes from the changed coordinates. In your example of four digit code prefixes, this would be +/- 1°.

I did something along those lines here: https://github.com/bocops/open-geotiling/blob/28609bd6c0a467bc22a18fe76cfa5d82cb52c3ff/java/org/bocops/opengeotiling/OpenGeoTile.java#L283

**Comment by floyernick** [comment]
> The easiest would be to get the underlying lat/long of a plus code, then add/subtract a constant value for that block size, then create new codes from the changed coordinates. In your example of four digit code prefixes, this would be +/- 1°.
> 
> 
> 
> I did something along those lines here: https://github.com/bocops/open-geotiling/blob/28609bd6c0a467bc22a18fe76cfa5d82cb52c3ff/java/org/bocops/opengeotiling/OpenGeoTile.java#L283
> 
> 
> 
> You could of course also attempt this as simply a string manipulation issue, but then you'd have to take into account all sorts of carry and wrapping issues yourself.

Great, thank you!

**Comment by ppghijk** [comment]
ငါဝင်ကြည့်နေတာမင်းတို့သိမှန်းလည်းသိတယ် ငါလည်းဘာမှမလုပ်တတ်ပါဘူး  စတ်ဝင်စားလိုလိုက်ကြည်တာပါပဲ

**Comment by ppghijk** [comment]
ဒီအကောင့်ကိုမသုံးရတော့ဘူးလို့ဆိုလိုတာလား    အဲဒါဆိုမသုံးဘူး  ငါ့ကိုလည်းမနှောင့်ယှက်ပါနဲ့

**Comment by ppghijk** [comment]
ဒီအကောင့်မသုံးရဘူးလို့ဆိုလိုတာလား အဲဒါဆိုမသုံးဘူး  ငါကိုလည်း မဟက်ပါနဲ့ကွာ

**Comment by RiverMersey** [comment]
As English translates as:  Does this mean you don't have to use this account?




Get Outlook for Android







On Sun, Jul 12, 2020 at 3:43 PM +0100, "ppghijk" <notifications@github.com> wrote:
















ဒီအကောင့်မသုံးရဘူးလို့ဆိုလိုတာလား အဲဒါဆိုမသုံးဘူး  ငါကိုလည်း မဟက်ပါနဲ့ကွာ
