### ISSUE TITLE
Plus Code is wrong

### ISSUE THREAD

**Issue by prose1** [google/open-location-code#395]
The plus code for my business is pinned to an address in Alexandria VA.  My business is in Lugoff SC.  How do I remove the incorrect plus code and replace it with the correct plus code? Customers are seeing this on my Google My Business listing and calling from VA. 
![image](https://user-images.githubusercontent.com/68250396/87349806-ec2ba800-c524-11ea-9bf6-bad54a022de6.png)

Thank you in advance for any help. 

Patty

**Comment by drinckes** [comment]
Hi Patty - this is because the pin for your business in Google Maps is in Alexandria.

You will need to move it to the correct location in SC - then the plus code will be updated.

Best if it is your business is to claim it, using the Claim this business link, then move it.
