### ISSUE TITLE
Add link to emacs lisp implementation?

### ISSUE THREAD

**Issue by ookisan** [google/open-location-code#397]
There is an emacs lisp implementation at https://gitlab.liu.se/davby02/olc

Perhaps a link could be added, like there is one for common lisp? I've submitted a pull request to have it included in melpa (emacs lisp package repository), but until that is merged, if you want to use it, downloading from gitlab.liu.se and (optionally) compiling it is the only way to go.

**Comment by ookisan** [comment]
Now also available in MELPA (which pulls the code from gitlab.liu.se).

**Comment by zongweil** [comment]
Done - thanks for letting us know @ookisan!
