### ISSUE TITLE
Plus Minus Code - WHVX+64J-MINSK

### ISSUE THREAD

**Issue by abitrolly** [google/open-location-code#398]
It is the same short code, except for the deterministic "minus" part containing the locality. Locality is a table lookup, so this requires adding a table with localities the the standard. Filtered by population (>1mln people or the largest city in the square) to keep the list short. The has few advantages.

1. Plus Minus Codes can be decoded by offline tools
2. The code become machine readable (unlike short Plus Code with locality) and long code more human readable

Short Plus Ccodes with locality like "WHVX+64J, Minsk, Belarus" are not machine readable, because it is impossible to understand if text after the first comma is locality without making a request to external service. With Plus Minus Code WHVX+64J-MINSK you don't need the external heuristics.

**Comment by fulldecent** [comment]
This repository is related to plus codes. What you are referring to is not a plus code. I recommend that this issue be closed as out of project scope.

**Comment by abitrolly** [comment]
@fulldecent this is a proposed backward compatible extension to Google's plus code. Where should I send it to if not this project?

**Comment by fulldecent** [comment]
I think the Google Groups makes sense https://groups.google.com/forum/#!forum/open-location-code

**Comment by bilst** [comment]
From (newly updated) https://github.com/google/open-location-code/wiki/FAQ#reference-location-dataset :
The open source libraries support conversion to/from addresses using the latlng of the reference location. Callers will need to convert place names to/from latlng using a geocoding system.

Providing a global dataset isn't within scope of this project. For a potential free alternative, see [Open Street Map](https://wiki.openstreetmap.org/) and derived geocoding service [Nominatim](https://nominatim.org/).

**Comment by abitrolly** [comment]
Not sure I need plus codes then. https://what3words.com/ looks like a good alternative.

**Comment by shutyourbeak** [comment]
> Not sure I need plus codes then. https://what3words.com/ looks like a good alternative.

Depends on your use case. Ultimately W3W is not open source, nor is it scalable (i.e. variable granularity/accuracy) and it's not free. Its also not (IMHO) as easy to integrate into a database given the variable string lengths 🤷🏻‍♂️
