### ISSUE TITLE
plus.codes coder gives wrong location code

### ISSUE THREAD

**Issue by abitrolly** [google/open-location-code#399]
![image](https://user-images.githubusercontent.com/8781107/89194070-8c6a6f00-d5af-11ea-8b6d-a5aff2812fef.png)

The actual short code is WHVX+64J as shown in URL and not WHVX+64 as shown in the box below. I just hit this while writing #398.

**Comment by bilst** [comment]
Thanks for the report, but this project is only for the open source implementations of open location codes, not the plus.codes/map website. You might try the "feedback" option there.
