### ISSUE TITLE
have a unique icon / graphic identifier for open-location-code

### ISSUE THREAD

**Issue by kralo** [google/open-location-code#40]
If you want to use open location codes (or plus codes) it would be great to have a logo/icon, so if you reference it on sites or even print material, then you have some (additional, besides the plus) identifier. Maybe something like a geo-pointer with a plus inside it (or since it's from google a "g+"?)

**Comment by kralo** [comment]
like that, maybe
![path4147](https://cloud.githubusercontent.com/assets/3055678/13204588/e54277ae-d8d3-11e5-84ca-119f4e049751.png)

**Comment by morciej** [comment]
I believe I have a similar idea. Let's make it a plus sign inside the "copyleft" reverse C.
![plus codes logo](https://cloud.githubusercontent.com/assets/17895139/13836434/a3a5000c-ebbe-11e5-9746-3a39a9f3aaa2.jpg)
The advantages is that is makes a character that can be scribbled by hand.
Maybe we can combine them by putting that character inside of a pin? :-)

**Comment by drinckes** [comment]
We have a graphic designer working on something and will announce it in the coming months.
