### ISSUE TITLE
License information missing from Java pom.xml

### ISSUE THREAD

**Issue by jbaker-dstl** [google/open-location-code#402]
The Java `pom.xml` does not contain any licensing information (despite the whole project being licensed under ASL2), meaning that when the library is used within another project the information is missing when aggregated license files are generated.

**Comment by whatlimits** [comment]
- [ ] [intresting ]()

**Comment by fulldecent** [comment]
Recommended tags: <kbd>implementation</kbd> <kbd>project organization</kbd>

**Comment by fulldecent** [comment]
Thank you, are you able to please provide a PR for this?
