### ISSUE TITLE
Rust: Unnecessary unwrap

### ISSUE THREAD

**Issue by d023604** [google/open-location-code#407]
Unnecessary unwrap in interface.rs:51:20
Instead of checking and unwrapping, it's better to use `if let` or `match`
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap

**Comment by d023604** [comment]
Happy to address

**Comment by fulldecent** [comment]
Recommended tag: <kbd>implementation</kbd>

Please proceed to provide a PR here
