### ISSUE TITLE
Documentation Error in Contributing? 

### ISSUE THREAD

**Issue by d023604** [google/open-location-code#409]
In the Contributing documentation, the documentation states

> The Open Location Code project accepts and greatly appreciates code contributions! If you are contributing code to the project, consider joining the Open Location Code project on GitHub.

The link for joining the Open Location Code project on GitHub leads to [https://goo.gl/forms/T65peVtfQfEoDWeD3](Join the AMP Project on GitHub) 

Is this correct?

**Comment by zongweil** [comment]
Thanks for pointing that out. I removed that confusing line in https://github.com/google/open-location-code/pull/410.

As a side note, I saw you opened a few issues for minor changes in the Rust library. Feel free to send out PR's for those if you have time, and we'll have someone review them.
