### ISSUE TITLE
Decode gives #VALUE error

### ISSUE THREAD

**Issue by jayeshkumars** [google/open-location-code#416]
![image](https://user-images.githubusercontent.com/33157351/95958476-d036eb80-0e1e-11eb-972b-b347e4fa81af.png)
=OLCDecode(code) is giving a #VALUE error in excel.

**Comment by bilst** [comment]
Hi Kumar, if you're using the VBA library in Excel, you might try OLCDecode2Array(), which has the comment, "Same as OLCDecode but returns the coordinates in an array, easier to use within Excel."

Hopefully that works, but if not can you share the plus code you're trying to convert (hard to read the screenshot). Also if you highlight the cell with #VALUE!, is there any more detailed error message it shows that you can share?

**Comment by RiverMersey** [comment]
![image](https://user-images.githubusercontent.com/54508654/96042359-38102500-0e65-11eb-81f2-215c01981a34.png)

**Comment by jayeshkum** [comment]
> 
> 
> Hi Kumar, if you're using the VBA library in Excel, you might try OLCDecode2Array(), which has the comment, "Same as OLCDecode but returns the coordinates in an array, easier to use within Excel."
> 
> Hopefully that works, but if not can you share the plus code you're trying to convert (hard to read the screenshot). Also if you highlight the cell with #VALUE!, is there any more detailed error message it shows that you can share?

Worked like a charm, when referred to a cell! The formula not accepting the direct input. 
Plus code to decode: 7M3JHPXM+X8 (in Cell A1)
=OLCDecode(A1) returns #VALUE!
=OLCDecode2Array(A1) returns the array (Solves the purpose)

But,
=OLCDecode(7M3JHPXM+X8) or =OLCDecode2Array(7M3JHPXM+X8)

Doesn't work, excel wouldn't accept the + sign, even if I put it in quotes("").

**Comment by shmootker** [comment]
When I try the OLCDecode2Array(A1) I get just the Latitude value 11.599875 in this example.  How do I get the other values that are supposed to be provided like the longitude value to show up in Excel?  I've tried selecting columns and rows before entering the function as is described in Excel but all it does is just repeat the latitude value and not the other values of the array.
