### ISSUE TITLE
العراق ذي قار قلعة سكر قرية البو علي بيت الحاج سلمان  جابر

### ISSUE THREAD

**Issue by R930495** [google/open-location-code#424]
جيد جدا

**Comment by boehs** [comment]
> Iraq Dhi Qar Castle Sugar Albu Ali village House of Haj Salman Jaber

> Very good

من فضلك لا تتحدث عن أشياء لا علاقة لها بتحسين هذه التكنولوجيا هنا

> Please don't talk about things that have nothing to do with improving this technology here

**Comment by bilst** [comment]
For issues with specific places in Google Maps, you can report a problem here:
https://support.google.com/maps/answer/3094088
Thanks!
