### ISSUE TITLE
Typo in short form resolutions?

### ISSUE THREAD

**Issue by pathway** [google/open-location-code#426]
At https://github.com/google/open-location-code/wiki/Evaluation-of-Location-Encoding-Systems :

> They can also be used in a short form of four to seven characters, similar to telephone numbers and postcodes, within approximately 50km of the original location. Within approximately 2.5km of the original location they can be shortened further

I would expect to see the second part "they can be shortened further", to have an even coarser resolution than the "short form" (50km), but it says 2.5km.

Thanks for sharing!

**Comment by bocops** [comment]
In that paragraph

> Plus codes are 10 to 11 characters long. They can also be used in a short form of four to seven characters, similar to telephone numbers and postcodes, within approximately 50km of the original location. Within approximately 2.5km of the original location they can be shortened further, to just four to five characters.

50km and 2.5km don't refer to the resolution of the resulting code, but to the approximate vicinity of the original location in which the shortened code can be properly recovered.

For example, if your full code is **85CGPGV2+F7**, you can shorten it by removing the first four characters (**PGV2+F7**) while referencing a nearby location like **Castle Valley, Utah, USA**. As long as the referenced location is less distant than half the grid size of the level (which is where the approx. 50km comes from), it can be used to determine which of the many **????PGV2+F7** we actually mean. "Four to seven characters", in this case, refers to the following code precisions:
- XXXX+
- XXXX+XX
- XXXX+XXX

Similarly, if you shorten the original code by two more (**V2+F7**), we'd need a reference location less than approx. 2.5km away to properly recover the original location. So, we might be able to state something like "V2+F7, near the Twisted Donut Arch in Utah". "Four to five characters" here refers to either the "XX+XX" or "XX+XXX" format.
