### ISSUE TITLE
PHP language support

### ISSUE THREAD

**Issue by chinmaypurav** [google/open-location-code#427]
I would like to contribute to this project by adding a PHP code with the same algorithm. 
The only problem I am facing is with the RegEx part.

**Comment by fulldecent** [comment]
Recommended tag: implementation request

(but actually recommending to close as out-of-scope in #434)

**Comment by ben221199** [comment]
I wrote one for PHP: https://github.com/yocto/yoclib-openlocationcode-php. It is just the Java code converted to PHP. Only thing I have to do is fixing some things until all tests pass, before I will release the first official version.

**Comment by drinckes** [comment]
We're happy to link to external implementations, especially as we're not experts in every language. Best thing would be for either of you to complete your implementation and then add it to the wiki page  https://github.com/google/open-location-code/wiki/Other-Implementations
