### ISSUE TITLE
Specification needs to state about formatting for Right-to-left

### ISSUE THREAD

**Issue by fulldecent** [google/open-location-code#433]
A decision has been made about how to properly format plus codes in right-to-left pages.

That means that the codes "2222+3333" "3333+2222" as written exactly as you see them here has a specific meaning. And that meaning is only unambiguous with the decision above.

Source: https://github.com/google/open-location-code/issues/142

This decision is a specification and it needs to be noted as a requirement on https://github.com/google/open-location-code/blob/master/docs/specification.md

That other issue was closed prematurely.

**Comment by bocops** [comment]
The specification states as much, and has done so since 2019. :)

> Code digits and ordering do not change in RTL languages.

**Comment by fulldecent** [comment]
Recommended tag: <kbd>specification</kbd>
