### ISSUE TITLE
Rename main branch from master to main

### ISSUE THREAD

**Issue by fulldecent** [google/open-location-code#440]
Google projects are consistently making this change.

examples:
- https://groups.google.com/a/chromium.org/g/infra-dev/c/DtX5L__JYr0
- https://github.com/google/marl/issues/153

**Comment by fulldecent** [comment]
Recommended tag: <kbd>project organization</kbd>

**Comment by bilst** [comment]
Done! Local clones may need updating:
https://docs.github.com/ja/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes
