### ISSUE TITLE
Plus Codes capitalization inconsistent with marketing website

### ISSUE THREAD

**Issue by fulldecent** [google/open-location-code#441]
The [OLC naming guidelines](https://github.com/google/open-location-code/wiki/Naming-guidelines) specifies:

> [Plus codes] should not be capitalised...

However, the Google marketing website at https://maps.google.com/pluscodes/ repeatedly fails to follow these specifications. Plus codes is used in title case. (There are some cases where it is used in a heading, but context shows that headings are using sentence case, not title case.)

I understand that those projects maybe not be directly related to this repository and the website is not under version control here (it should be!) but please work with me. I have a lot of work to do here and need some help...

<img width="1446" alt="Screen Shot 2021-04-24 at 22 54 38" src="https://user-images.githubusercontent.com/382183/115978826-5495c400-a550-11eb-9217-bfff44567db3.png">

<img width="1446" alt="Screen Shot 2021-04-24 at 22 54 42" src="https://user-images.githubusercontent.com/382183/115978828-56f81e00-a550-11eb-8ae6-effecebc68fc.png">

**Comment by fulldecent** [comment]
Recommended tag: <kbd>documentation</kbd>

**Comment by bilst** [comment]
Unfortunate given how the documentation here was so insistent on lowercase, but Google's new style preference is "Plus Codes". Will keep this issue to track inconsistencies in code/documentation.

**Comment by fulldecent** [comment]
Understood. I'm on it.

**Comment by fulldecent** [comment]
This issue is partially fixed at https://github.com/google/open-location-code/pull/463
