### ISSUE TITLE
Wrong plus code in Google maps 

### ISSUE THREAD

**Issue by Sujatha1357** [google/open-location-code#466]
Google maps shows the wrong plus code for Hindustan Institute of technology

**Comment by bocops** [comment]
A plus code is just a different representation for a location. If Google Maps shows the wrong plus code, then it must use the wrong lat/long coordinates for your point of interest. You will have to take that up with Google either via suggesting a change for the POI, or via general feedback.

**Comment by Dmitry-Sokolov** [comment]
@Sujatha1357  I have similar problem, but I find the problem in the my code.
According to the description inside the "open-location-code/openlocationcode.js"
const latitude = 47.365590 
const longitude = 8.524997
var code = openLocationCode.encode(latitude, longitude);

You need first to have latitude/longitude not in the string format and the second, the order should be .encode(latitude, longitude).
