### ISSUE TITLE
best_street_address is not shown in the JSON result

### ISSUE THREAD

**Issue by 365ejk** [google/open-location-code#477]
Has anyone noticed ?

For example,
https://plus.codes/api?address=796RWF8Q+WF&key=YOURKEY
or
https://plus.codes/api?address=796RWF8Q%2BWF&key=YOURKEY

does not show street address anymore.
Document example: https://github.com/google/open-location-code/wiki/Plus-codes-API

**Comment by bilst** [comment]
Unfortunately the Plus Codes API doesn't return best_street_address as of a few months ago. It wasn't directly related to plus codes, and its functionality is available in other Google APIs.

For an alternative, see other geocoding APIs like Google Maps Platform (includes plus codes in results, large monthly free quota):
https://developers.google.com/maps/documentation/geocoding/start#reverse

Or Nominatim (free, see https://operations.osmfoundation.org/policies/nominatim/ for API usage etiquette or build your own server: https://nominatim.org/release-docs/latest/admin/Installation/):
https://nominatim.org/release-docs/develop/api/Reverse/
