### ISSUE TITLE
Patent or licensing of the code

### ISSUE THREAD

**Issue by karussell** [google/open-location-code#48]
The implementation is Apache Licensed which makes patents put on the code of the implemention transferred to the user (automatically), which is good but still not enough, I think but not sure :)

E.g. the costs for using the **open location code** itself is unclear to me. Can you point me to a license part that guarantees that using this code in e.g. competitive maps or routing services will be free for the provider and its customers? Or is it automatically assumed that the "data"/outcome of the algorithm is free for anyone?

**Comment by drinckes** [comment]
It is certainly our intent to enable anyone to use it for anything at no cost, and with minimal encumbrances.

The implementation is Apache 2 licensed, meaning that the recipient gets a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright and patent license to it (see sections 2 & 3). If you need more information about the impact of using this software in a business context please see a local lawyer to help you.

**Comment by karussell** [comment]
@drinckes thanks for the clear and helpful answer!
