### ISSUE TITLE
Implementation requirement to recover a full Open Location Code from a short code/global address at odds with "Works Offline" design requirement

### ISSUE THREAD

**Issue by scruss** [google/open-location-code#49]
Given *MQPX9G Nairobi, Kenya*, one cannot recover the full OLC without a network connection or gazetteer. This breaks the design requirements to work offline.

Suggested is a "level 0" implementation describing only full OLCs with no gazetteer requirement, as could be encoded/decoded by an embedded device with no network access.

(Short codes are also culturally sensitive. *845R+3C Stanley, East Falkland* and *845R+3C Puerto Argentino, Islas Malvinas* are the [same place](https://plus.codes/38W4845R+3C) to different people. Perhaps best to quietly drop the "global address" term.)

**Comment by drinckes** [comment]
Global codes (796rwf8q+wf) work offline. A local code (wf8q+wf), will work offline within half a degree - roughly 50km - of the location.

A local code with a locality will require some service to geocode it, yes. I don't think that materially changes the claim.

The flexibility that multiple different locality names can be used for the same location is an advantage specifically for the reason you mention. Locations in disputed territories can be addressed appropriately to the person doing the addressing, but without the code component changing.
