### ISSUE TITLE
Please move all wiki articles into the repository // MOVE SHORT CODE SPEC

### ISSUE THREAD

**Issue by fulldecent** [google/open-location-code#490]
Please move all the wiki articles into the repository.

There are currently normative statements in the Wiki. Those should be under code control and should be open to discussion/PR inside this repository.

---

Requesting that these be copied as-is for now (even with broken links). And then everybody can help to clean them up together.

I myself have many corrections to make to those as per https://github.com/google/open-location-code/pull/463. And maybe if all the files are here this can help us make progress on all these things.

**Comment by drinckes** [comment]
New documentation tree (using existing names) I plan to move things to. That will empty the wiki and then it can be turned off.

## Existing files
- `Documentation`  (renamed from `docs`)
  - `reference`
    - `comparison.adoc`: Comparison of location encoding systems (was previously in repo, got moved to wiki, move back)
  - `specification`
    - `API.md`: API requirements for implementations
    - `olc_definition.adoc: Background/description of Open Location Code project
    - `specification.md`: Open Location Code technical specification
      - merge in `API.md`
      - merge in [guidelines for shortening codes](https://github.com/google/open-location-code/wiki/Guidance-for-shortening-codes) from the wiki

## From wiki
- `Documentation`
  - `README.md` from [Home](https://github.com/google/open-location-code/wiki) - it will want some work adding in the other documents
  - [Other implementations](https://github.com/google/open-location-code/wiki/Other-Implementations)
  - `specification`
    - [Naming Guidelines](https://github.com/google/open-location-code/wiki/Naming-guidelines)
- `wiki`
  - [FAQ](https://github.com/google/open-location-code/wiki/FAQ)
  - [Field Collection Data Practices](https://github.com/google/open-location-code/wiki/Field-Data-Collection-Practices)
  - [plus.codes website API](https://github.com/google/open-location-code/wiki/Plus-codes-API)
  - [Supporting Plus Codes in GIS software](https://github.com/google/open-location-code/wiki/Supporting-plus-codes-in-GIS)
  - [Supporting Plus Codes in your app](https://github.com/google/open-location-code/wiki/Supporting-plus-codes-in-your-app)
  - [Using Plus Codes in spreadsheets](https://github.com/google/open-location-code/wiki/Using-plus-codes-in-spreadsheets)
  - [Who is using OLC?](https://github.com/google/open-location-code/wiki/Using-plus-codes-in-spreadsheets)

**Comment by drinckes** [comment]
Todo(@drinckes): Merge API.md and short code guidelines into specification.md

**Comment by fulldecent** [comment]
Perfect, thank you. Hopefully this makes it easier to manage. I see 

- [ ] Merge API.md and short code guidelines into specification.md, but I have to do some actual work now too.

Are there any other high-priority action items directly related to this wiki merge that you wanted to highlight now?
