### ISSUE TITLE
Support for extraterrestrial places

### ISSUE THREAD

**Issue by ben221199** [google/open-location-code#499]
For now, OLC is enough to give every location on earth a code. However, with NASA and Elon Musk doing much space stuff lately, I think that there should be thought about extending OLC for extraterrestrial places like Mars and the moon. Considering that Google has a map of Mars (https://www.google.com/mars/) and the moon (https://www.google.com/moon/) on their site, I think it could be really useful too.

**Comment by bilst** [comment]
OLC is a transformation of latitude and longitude, so its current implementation will work as well on Mars and the moon, which have standards for latitude and longitude.
