### ISSUE TITLE
Findind nearest neighbour/shortest path and traversal

### ISSUE THREAD

**Issue by chakravarthyvp** [google/open-location-code#50]
Hi All,

```
 I'm evaluating OLC for a hands on project to snap a grid cell based on a gps location. The proposal is to create Areas that are hashed for faster look ups on caches. Basically i'm playing around mapping a road network using OLC. There does not seem to be an API or a simple understanding of how to traverse the neighbours..

 The problem is: Supposing there are 100Meter by 100Meter precision areas mapping to different roads that pass through, I'm trying to find what is the traversal (algorithm) route to my destination.
 Any light on this is highly appreciated...
```

Best Regards
CVP

**Comment by drinckes** [comment]
The question is largely going to depend on what resolution you require, whether you need all squares or can skip some.

In general, you can just compute in steps equal to the resolution of the areas. For example, a code such as 8FVC8FXR+ has the resolution of 1/400th of a degree.

Therefore, if you compute the center lat/lng, if you step 1/400th of a degree east or west, you'll get the neighbouring code.

Does that help?

**Comment by drinckes** [comment]
(If you need more information, feel free to reopen, or switch to the public mailing list at https://groups.google.com/forum/#!forum/open-location-code)
