### ISSUE TITLE
Ada implementation

### ISSUE THREAD

**Issue by malaise** [google/open-location-code#504]
Interested about an implementation of OLC in Ada?

I have translated the Cpp version and it is ready in my own environment (https://github.com/malaise/ada/tree/master/usr/olc).
The differences from the Cpp verrsions are:
- Ada typing ensures that input lat and long are within the correct range (-90 - 90) and (-180 - 180)
- Codes that are too long are rejected as invalid instead of silently truncated (which leads some coding tests to be KO)
Except the restriction above, the tests are OK.

**Comment by bilst** [comment]
Neat! Easiest option would probably to add a link to your repo, e.g. like we have for Emacs Lisp:
https://github.com/google/open-location-code/tree/main/emacs

Happy to review a PR.

**Comment by malaise** [comment]
OK then.

I now have:
* made standalone the library and test program
* updated the test script so that it can run the "open-location-map" tests (except for lat-long out of bounds and for codes that are too long)
* Added a short README.md
So I think that you can add the "ada" directory with the link to the URL in my first post.

Thank you

**Comment by drinckes** [comment]
Added it to the wiki: https://github.com/google/open-location-code/wiki/Other-Implementations
