### ISSUE TITLE
Link to source of plus.codes site

### ISSUE THREAD

**Issue by jyasskin** [google/open-location-code#53]

**Comment by buge** [comment]
Assigning to Doug who wrote the site. It would indeed be nice to add it to this repo.

**Comment by drinckes** [comment]
I'm not going to add it to this repo, I may create another repo in the future with it but I need to do some refactoring before that happens.

@jyasskin did you have anything in particular you were interested in?

**Comment by drinckes** [comment]
If there's specific questions I'm happy to respond to those - like how are searches parsed etc. @jyasskin feel free to reopen this, or use the public mailing list, whatever is best for you.
