### ISSUE TITLE
In dart Encoded LatLng and Decoded LatLng  both are different

### ISSUE THREAD

**Issue by uumerazeem** [google/open-location-code#551]
decode didn't work well 
<img width="518" alt="Screenshot 2023-01-26 at 3 00 34 PM" src="https://user-images.githubusercontent.com/66119646/214808231-3878acea-b7e9-40af-9866-d2ece96a31f2.png">

**Comment by bocops** [comment]
Plus codes identify areas, not single locations. If you encode lat/lng coordinates, you will get a plus code for an area containing those coordinates, but not necessarily centered on it.

If you decode a plus code, you will typically get the center coordinate for that area, which might differ slightly from your original input.

**Comment by uumerazeem** [comment]
Is there any way to get it as same as original?

**Comment by bocops** [comment]
Note that I just updated my above comment to include the possibility of two opposing edges being returned.

Encoding will _always_ return an area, so decoding will nearly always result in coordinates that are slightly different. However, in your example the difference is something like .000004 degrees, or .5 meters. That's probably within the margin of error of most GPS devices, and should be OK for most addressing use cases.

If you need to be more precise, you could increase the `codeLength` value to 12 or 13. There would potentially still be a difference between input and ouput, but that difference should be << 1m.

**Comment by uumerazeem** [comment]
Thank you for your time. it works fine now.
