### ISSUE TITLE
Python implementation needs documentation, examples

### ISSUE THREAD

**Issue by nealmcb** [google/open-location-code#557]
An easy way to start this is via some docstrings, in combination with #417.

Here are a few tips for those who peruse issues, in the meantime.

Some of the main functions, with defaults:
* `openlocationcode.encode(latitude, longitude, codeLength=10)`
* `openlocationcode.decode(code)`

Examples:

```
>>> from openlocationcode import openlocationcode as olc

>>> olc.encode(40,-105)
'85GQ2222+22'
>>> olc.decode('85GQ2222+22')
[40.0, -105.0, 40.000125, -104.999875, 40.0000625, -104.9999375, 10]
>>> olc.encode(40,-105, codeLength=4)
'85GQ0000+'
>>>olc.decode('85GQ0000+')
40.0, -105.0, 41.0, -104.0, 40.5, -104.5, 4]
```

**Comment by drinckes** [comment]
I'm going to add a note to #417 and close this as a duplicate.
