### ISSUE TITLE
Flutter package to store and query open location codes in Firebase

### ISSUE THREAD

**Issue by dryprogrammer** [google/open-location-code#569]
Is there any demand for a dart package to store and query open location codes in Firebase, like this package for geohash that can query by radius?
https://pub.dev/packages/geoflutterfire

It could be useful since Google Maps geocoding API returns "Open Location Code".
Ex from reverseGeocode:
```
    plus_code: {
      compound_code: "WQ58+4Q3 Muju-gun, Jeollabuk-do, South Korea",
      global_code: "8Q79WQ58+4Q3",
    }
```

I couldn't find anything on this topic. Appreciate any input.

**Comment by dryprogrammer** [comment]
To be clear, there is a current dart package that can be leveraged as it provides:
- encode and decode codes,
- shorten them relative to a reference location, and
- recover a location from a short code and a reference location given as latitude/longitude pair

https://pub.dev/packages/open_location_code

**Comment by drinckes** [comment]
That's really cool, unfortunately out of scope for this repo.
