### ISSUE TITLE
Add cautionary notice

### ISSUE THREAD

**Issue by jidanni** [google/open-location-code#571]
We see videos of Plus Codes / Open Location Codes saving the day for various rural / slum areas. One needs to be aware however that sometimes Plus Codes should not be the sole or even primary address:

Imagine a city with a perfect rectangular street grid, oh, and tilted 45 degrees from the north to boot. Here a traditional "418 34th St.", "1103 Avenue D" address is far superior to any Plus Code, at least in helping a resident get from A to B, without the help of electronic devices.

Therefore https://github.com/google/open-location-code/wiki/FAQ  and even https://maps.google.com/pluscodes/technology/ need to mention some cautions. Else let's say some local government goes hog wild with Plus Codes, with the final result being the entire Plus Code project unfairly gets a bad reputation!

**Comment by drinckes** [comment]
I think the FAQ is fairly clear that plus codes are used in situations where either the existing street addresses are not helpful or where they don't exist. Beyond that I have faith that people are able to determine the most appropriate solution for their needs and their situation. I don't think we need additional words there.
