### ISSUE TITLE
CLA fails when user has two addresses

### ISSUE THREAD

**Issue by jidanni** [google/open-location-code#573]
CLA fails. Reason: the user's GitHub account is associated with jidanni@jidanni.org .

![Screenshot 2024-04-06 08 44 35](https://github.com/google/open-location-code/assets/1230959/1ba81095-93eb-4629-bc00-69eb54e2e55a)

**Comment by drinckes** [comment]
I think this is resolved now, yes? (At least it appears we think you have a CLA.) If not, reopen and let me know what the issue is.
