### ISSUE TITLE
plus.codes/map needs scale bar

### ISSUE THREAD

**Issue by jidanni** [google/open-location-code#576]
https://plus.codes/map needs a scale bar!
That way we can get an idea of how wide the grids (when enabled in the menu) shown are, especially in rural areas.

**Comment by bocops** [comment]
The plus codes map is not handled by this repository, but is something created by Google, mostly an extension of Google Maps at this point. You might be better off by raising that issue via feedback on that page.

This issue should be closed here.

**Comment by jidanni** [comment]
OK, I sent them Feedback.

**Comment by drinckes** [comment]
Thanks all, closing here.
