### ISSUE TITLE
[#10577](https://github.com/rubocop/rubocop/pull/10577)

### ISSUE THREAD

**Issue by nilestimothy78** [google/open-location-code#593]
[#10577](https://github.com/rubocop/rubocop/pull/10577)

- [ ] [#10577](https://github.com/rubocop/rubocop/pull/10577)[#10577](https://github.com/rubocop/rubocop/pull/10577)[#10577](https://github.com/rubocop/rubocop/pull/10577)[#10577](https://github.com/rubocop/rubocop/pull/10577)[](url)

**Comment by drinckes** [comment]
I think you got the wrong repo
