### ISSUE TITLE
different plus codes results of the plus code API search and the plus code webpage search

### ISSUE THREAD

**Issue by unfassbarstephan** [google/open-location-code#61]
I noticed slightly different plus codes results of a specific point between the plus code API search and the plus code webpage search.

E. g.:

point (Lat,Lon): [50.963400,13.939100](http://maps.google.com/?q=50.963400,13.939100&t=h)

search result api: [9F2MXW7Q+8P](https://plus.codes/api?address=50.963400,13.939100)

search result webpage: [9F2MXW7Q+9J](https://plus.codes/9F2MXW7Q+9J)

**Comment by drinckes** [comment]
Thanks for this!

Lat/lng queries are getting sent to the Google Geocoding API. It's responding with a geocoded location, and the code is being generated from that position.

In this case, the Google Geocoded response is far enough (by a few meters) from the lat/lng position that we're generating an code for that position (50.9633043, 13.9392803) not the requested position (50.963400,13.939100).

Fix is for the API to detect lat/lng queries and converting them to a code.

On this now.

**Comment by drinckes** [comment]
Thanks again for reporting. The API has been updated to handle lat/lng requests properly and restarted. Please do let us know if you see any other problems.

**Comment by drinckes** [comment]
BTW @unfassbarstephan if you're doing a lot of requests (2 per second) could you contact me using my github name @ google.com please?

**Comment by unfassbarstephan** [comment]
Thank you for your fast fix! At first sight, it seems to work perfecty.
