### ISSUE TITLE
dead links in Sheets documentation

### ISSUE THREAD

**Issue by keturn** [google/open-location-code#637]
https://github.com/google/open-location-code/blob/dfcebc905b81c3d9c987f7b3ac6e992f1e8710c6/Documentation/Reference/Using_Spreadsheets.md?plain=1#L11 links to a YouTube playlist to show how to use the add-on. That playlist no longer exists.

I dug up links to those videos from the Wayback Machine, but youtube claims the videos no longer exist.

The channel https://www.youtube.com/c/pluscodes still exists, but YouTube claims it has no content.

**Comment by bocops** [comment]
Updated links in #638.
