### ISSUE TITLE
VBA code version: error in sub-subscript

### ISSUE THREAD

**Issue by maimizuno** [google/open-location-code#66]
LIne 601 (test suite):

MsgBox ("IsFull test " + CStr(i) + ", expected: " + CStr(validity(i)(2) = "true") + ", actual: " + CStr(f))

This (*)SHOULD BE(*):

MsgBox ("IsFull test " + CStr(i) + ", expected: " + CStr(validity(i)(3) = "true") + ", actual: " + CStr(f))

(Notice: the sub-subscript "2" was copied from, presumably, line 597 and was not updated (line 600 was properly updated when copied from line 596).

**Comment by drinckes** [comment]
Thanks - am investigating.

**Comment by drinckes** [comment]
Thanks! I've merged the change into the master branch.
