### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by eselkin** [google/open-location-code#78]
I created a Swift 3.x implementation based off your python/rust/C++ code and it is available as a cocoapod for people who want to use it in developing iOS applications. If you'd rather that I just give you the code (since it's 99% yours), I'd be more than happy to.

The cocoapod is [here](https://cocoapods.org/pods/OpenLocationCode)

**Comment by drinckes** [comment]
Oh that's great! I'll create a /swift directory and link to your cocoapod from the README if that's ok.

**Comment by eselkin** [comment]
It's perfectly fine with me... I'll be adding more to the framework shortly. As of now all it does is decode and encode. It doesn't do any of the "find nearest" stuff yet.
